---
title: "Introduction to spaceRATScaffolds"
output: 
  BiocStyle::html_document:
    toc: true
    toc_depth: 2
    highlight: pygments
author: "Søren Helweg Dam"
date: "Last updated: `r format(Sys.Date(), '%Y.%m.%d')`"
vignette: >
    %\VignetteIndexEntry{Introduction to spaceRATScaffolds}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Installation

*Install from GitHub*

``` {r install, eval = FALSE}
remotes::install_github("shdam/spaceRATScaffolds", build_vignettes = TRUE)
```

# Introduction

This package contains scaffolds used for
[spaceRAT](https://github.com/shdam/spaceRAT). See the package
vignettes for instructions how to build your own scaffold
and use the prebuilt scaffolds.

The current `spaceRAT` scaffolds include:

``` {r lists}

library("spaceRATScaffolds")

listScaffolds()

listDatasets()

listConverters()

```

## Preload a scaffold

Scaffolds are stored on [Zenodo](https://zenodo.org/records/10142340).
Preload a scaffold with:

```{r preload}

scaffoldName <- "DMAP"

scaffold <- getScaffold(
    name = scaffoldName,
    path = "scaffolds/",
    timeout = 120,
    store = FALSE
    )
```

## Get scaffold information

```{r help, eval=FALSE}

utils::help(scaffoldName)
```


# Session Info

```{r session info}
sessionInfo()
```
